Repository 100-hours-a-week/8-pumati-ai, pull requests merged in 2025-05, with the labels that each got.

#16 Chore/12 comment parameter tuning
  app/context_construction/query_rewriter.py
  app/model_inference/loaders/gemma_loader.py
Labels: 🔧 chore

#19 Refactor/17 comment code quality
  app/context_construction/query_rewriter.py
  app/fast_api/endpoints/comment_router.py
  app/main.py
  app/model_inference/loaders/gemma_loader.py
  requirements.txt
Labels: ✨ feat, ♻️ refactor

#21 Feat/20 comment validation
  app/context_construction/query_rewriter.py
  app/fast_api/endpoints/comment_router.py
  app/model_inference/loaders/gemma_loader.py
Labels: ✨ feat

#64 Feat/62 comment fin
  .github/workflows/cicd-cpu-dev.yml
  app/context_construction/query_rewriter.py
  app/fast_api/endpoints/comment_router.py
  app/services/comment_service.py
Labels: ✨ feat

#65 [cpu] merge final ai-comment
  .dockerignore
  .github/workflows/README.md
  .github/workflows/cicd-cpu-dev.yml
  .github/workflows/cicd-cpu-prod.yml
  .github/workflows/cicd-dev.yml
  Dockerfile.cpu
  app/__init__.py
  app/archive/comment_gemma_loader.py
  app/archive/fortune_gemma_loader.py
  app/comment_generation_cpu/comment_clova_loader.py
  app/comment_generation_cpu/comment_guardrails.py
  app/comment_generation_cpu/comment_service.py
  app/config/constants.py
  app/config/settings.py
  app/context_construction/prompts/comment_prompt.py
  app/context_construction/prompts/fortune_prompt.py
  app/context_construction/query_rewriter.py
  app/fast_api/__init__.py
  app/fast_api/controllers/__init__.py
  app/fast_api/endpoints/comment_router.py
  app/fast_api/endpoints/fortune_router.py
  app/fast_api/schemas/__init__.py
  app/fast_api/schemas/comment_schemas.py
  app/fast_api/schemas/fortune_schema.py
  app/main_cpu.py
  app/model_inference/comment_inference_runner.py
  app/model_inference/fortune_inference_runner.py
  app/model_inference/inference_runner.py
  app/model_inference/loaders/HyperCLOVA_loader.py
  app/model_inference/loaders/comment_loader.py
  app/model_inference/loaders/hyperclova_loader.py
  app/model_inference/output_guardrails.py
  app/services/comment_service.py
  app/services/fortune_service.py
  app/test/__init__.py
  app/test/post_server.py
  app/test/receive_server.py
  app/utils/auth.py
  app/utils/image_utils.py
  app/utils/logger.py
  app/utils/prompt_utils.py
  requirements.cpu.txt
Labels: ✨ feat

#73 [feat] 운세 name -> nickname 필드 변경
  app/context_construction/prompts/fortune_prompt.py
  app/fast_api/endpoints/fortune_router.py
  app/fast_api/schemas/fortune_schema.py
  app/model_inference/fortune_inference_runner.py
  requirements.cpu.txt
Labels: ✨ feat

#74 feat: [cpu]version error 수정
  .github/workflows/cicd-cpu-dev.yml
  app/fast_api/endpoints/comment_router.py
  requirements.cpu.txt
Labels: ✨ feat

#77 fix: [cpu] ReduceRetry
  app/services/comment_service.py
Labels: 🐛 fix

#78 fix: [cpu]KoEnName
  app/fast_api/endpoints/comment_router.py
  app/services/comment_service.py
Labels: 버그-일반

#80 refactoring: [cpu]summary
  app/services/comment_service.py
Labels: ♻️ refactor
